name: Build & Cache Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - docs/**
      - .gitignore
      - README.md
      - LICENSE
jobs:
  build-installation-images:
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/maximize-build-space@v10
        with:
          overprovision-lvm: true
          remove-android: true
          remove-dotnet: true
          remove-haskell: true

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          logger: pretty

      - name: Cachix setup
        uses: cachix/cachix-action@v15
        with:
          authToken: ${{ secrets.CACHIX_TOKEN }}
          name: notashelf

      - name: Set default git branch (to reduce log spam)
        run: git config --global init.defaultBranch main

      - name: Build installation media
        run: nix build .#nixosConfigurations."gaea".config.system.build.toplevel

      - name: Build airtight recovery/maintenance media
        run: nix build .#nixosConfigurations."erebus".config.system.build.toplevel
