name: Check Flake Formatting

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.nix"
      - ".github/workflows/check.yml"
  push:
    paths:
      - "**.nix"
      - ".github/workflows/check.yml"

jobs:
  check:
    uses: ./.github/workflows/prelude.yml
    secrets:
      GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    with:
      command: |
        nix run nixpkgs#alejandra -- \
        --exclude ./flake/pkgs/packages/nicksfetch/generated.nix \
        --exclude ./flake/pkgs/packages/plymouth-themes/generated.nix -c .
