name: Check Flake Formatting

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.nix"
      - ".github/workflows/check.yml"
  push:
    paths:
      - "**.nix"
      - ".github/workflows/check.yml"

jobs:
  cchecks:
    name: Check expressions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
            experimental-features = nix-command flakes
      - run: |
          nix run nixpkgs#alejandra -- \
          --exclude ./flake/pkgs/packages/nicksfetch/generated.nix \
          --exclude ./flake/pkgs/packages/plymouth-themes/generated.nix -c .
